# .github/workflows/ci.yml

name: CI Pipeline for Credit Risk Model

# --- Triggers ---
# This workflow runs on every push to the 'main' branch
# and on every pull request targeting the 'main' branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# --- Jobs ---
# A workflow is made up of one or more jobs that run in parallel or sequentially.
jobs:
  # The 'build-and-test' job
  build-and-test:
    # The type of virtual machine to run the job on.
    # 'ubuntu-latest' is a standard and cost-effective choice.
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out the repository code
      # This downloads your code into the runner.
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      # Specifies the Python version to use.
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install project dependencies
      # Caches dependencies to speed up subsequent runs.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # We also need our testing dependencies
          pip install pytest httpx anyio trio

      # Step 4: Run the test suite
      # Executes the tests using pytest.
      - name: Run tests with pytest
        run: |
          pytest